/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApplicationInstance service. Represents a row in the &quot;bibboxdocker_ApplicationInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see ApplicationInstance
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceImpl
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceModelImpl
 * @generated
 */
@ProviderType
public interface ApplicationInstanceModel extends BaseModel<ApplicationInstance>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application instance model instance should use the {@link ApplicationInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this application instance.
	 *
	 * @return the primary key of this application instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application instance.
	 *
	 * @param primaryKey the primary key of this application instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application instance ID of this application instance.
	 *
	 * @return the application instance ID of this application instance
	 */
	public long getApplicationInstanceId();

	/**
	 * Sets the application instance ID of this application instance.
	 *
	 * @param applicationInstanceId the application instance ID of this application instance
	 */
	public void setApplicationInstanceId(long applicationInstanceId);

	/**
	 * Returns the group ID of this application instance.
	 *
	 * @return the group ID of this application instance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this application instance.
	 *
	 * @param groupId the group ID of this application instance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this application instance.
	 *
	 * @return the company ID of this application instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this application instance.
	 *
	 * @param companyId the company ID of this application instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this application instance.
	 *
	 * @return the user ID of this application instance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this application instance.
	 *
	 * @param userId the user ID of this application instance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this application instance.
	 *
	 * @return the user uuid of this application instance
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this application instance.
	 *
	 * @param userUuid the user uuid of this application instance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this application instance.
	 *
	 * @return the user name of this application instance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this application instance.
	 *
	 * @param userName the user name of this application instance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this application instance.
	 *
	 * @return the create date of this application instance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this application instance.
	 *
	 * @param createDate the create date of this application instance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application instance.
	 *
	 * @return the modified date of this application instance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application instance.
	 *
	 * @param modifiedDate the modified date of this application instance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the instance ID of this application instance.
	 *
	 * @return the instance ID of this application instance
	 */
	@AutoEscape
	public String getInstanceId();

	/**
	 * Sets the instance ID of this application instance.
	 *
	 * @param instanceId the instance ID of this application instance
	 */
	public void setInstanceId(String instanceId);

	/**
	 * Returns the name of this application instance.
	 *
	 * @return the name of this application instance
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this application instance.
	 *
	 * @param name the name of this application instance
	 */
	public void setName(String name);

	/**
	 * Returns the short name of this application instance.
	 *
	 * @return the short name of this application instance
	 */
	@AutoEscape
	public String getShortName();

	/**
	 * Sets the short name of this application instance.
	 *
	 * @param shortName the short name of this application instance
	 */
	public void setShortName(String shortName);

	/**
	 * Returns the baseurl of this application instance.
	 *
	 * @return the baseurl of this application instance
	 */
	@AutoEscape
	public String getBaseurl();

	/**
	 * Sets the baseurl of this application instance.
	 *
	 * @param baseurl the baseurl of this application instance
	 */
	public void setBaseurl(String baseurl);

	/**
	 * Returns the folder name of this application instance.
	 *
	 * @return the folder name of this application instance
	 */
	@AutoEscape
	public String getFolderName();

	/**
	 * Sets the folder name of this application instance.
	 *
	 * @param folderName the folder name of this application instance
	 */
	public void setFolderName(String folderName);

	/**
	 * Returns the application of this application instance.
	 *
	 * @return the application of this application instance
	 */
	@AutoEscape
	public String getApplication();

	/**
	 * Sets the application of this application instance.
	 *
	 * @param application the application of this application instance
	 */
	public void setApplication(String application);

	/**
	 * Returns the version of this application instance.
	 *
	 * @return the version of this application instance
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this application instance.
	 *
	 * @param version the version of this application instance
	 */
	public void setVersion(String version);

	/**
	 * Returns the status of this application instance.
	 *
	 * @return the status of this application instance
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this application instance is status.
	 *
	 * @return <code>true</code> if this application instance is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this application instance is status.
	 *
	 * @param status the status of this application instance
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the deleted of this application instance.
	 *
	 * @return the deleted of this application instance
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this application instance is deleted.
	 *
	 * @return <code>true</code> if this application instance is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this application instance is deleted.
	 *
	 * @param deleted the deleted of this application instance
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the shortdescription of this application instance.
	 *
	 * @return the shortdescription of this application instance
	 */
	@AutoEscape
	public String getShortdescription();

	/**
	 * Sets the shortdescription of this application instance.
	 *
	 * @param shortdescription the shortdescription of this application instance
	 */
	public void setShortdescription(String shortdescription);

	/**
	 * Returns the description of this application instance.
	 *
	 * @return the description of this application instance
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this application instance.
	 *
	 * @param description the description of this application instance
	 */
	public void setDescription(String description);

	/**
	 * Returns the adminnode of this application instance.
	 *
	 * @return the adminnode of this application instance
	 */
	@AutoEscape
	public String getAdminnode();

	/**
	 * Sets the adminnode of this application instance.
	 *
	 * @param adminnode the adminnode of this application instance
	 */
	public void setAdminnode(String adminnode);

	/**
	 * Returns the maintenance of this application instance.
	 *
	 * @return the maintenance of this application instance
	 */
	@AutoEscape
	public String getMaintenance();

	/**
	 * Sets the maintenance of this application instance.
	 *
	 * @param maintenance the maintenance of this application instance
	 */
	public void setMaintenance(String maintenance);

	/**
	 * Returns the ismaintenance of this application instance.
	 *
	 * @return the ismaintenance of this application instance
	 */
	public boolean getIsmaintenance();

	/**
	 * Returns <code>true</code> if this application instance is ismaintenance.
	 *
	 * @return <code>true</code> if this application instance is ismaintenance; <code>false</code> otherwise
	 */
	public boolean isIsmaintenance();

	/**
	 * Sets whether this application instance is ismaintenance.
	 *
	 * @param ismaintenance the ismaintenance of this application instance
	 */
	public void setIsmaintenance(boolean ismaintenance);

	/**
	 * Returns the installlog of this application instance.
	 *
	 * @return the installlog of this application instance
	 */
	@AutoEscape
	public String getInstalllog();

	/**
	 * Sets the installlog of this application instance.
	 *
	 * @param installlog the installlog of this application instance
	 */
	public void setInstalllog(String installlog);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstance applicationInstance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstance> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstance toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}