/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApplicationInstanceStatus service. Represents a row in the &quot;bibboxdocker_ApplicationInstanceStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceStatusImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see ApplicationInstanceStatus
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceStatusImpl
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationInstanceStatusModelImpl
 * @generated
 */
@ProviderType
public interface ApplicationInstanceStatusModel extends BaseModel<ApplicationInstanceStatus>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application instance status model instance should use the {@link ApplicationInstanceStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this application instance status.
	 *
	 * @return the primary key of this application instance status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application instance status.
	 *
	 * @param primaryKey the primary key of this application instance status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application instance status ID of this application instance status.
	 *
	 * @return the application instance status ID of this application instance status
	 */
	public long getApplicationInstanceStatusId();

	/**
	 * Sets the application instance status ID of this application instance status.
	 *
	 * @param applicationInstanceStatusId the application instance status ID of this application instance status
	 */
	public void setApplicationInstanceStatusId(long applicationInstanceStatusId);

	/**
	 * Returns the group ID of this application instance status.
	 *
	 * @return the group ID of this application instance status
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this application instance status.
	 *
	 * @param groupId the group ID of this application instance status
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this application instance status.
	 *
	 * @return the company ID of this application instance status
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this application instance status.
	 *
	 * @param companyId the company ID of this application instance status
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this application instance status.
	 *
	 * @return the user ID of this application instance status
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this application instance status.
	 *
	 * @param userId the user ID of this application instance status
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this application instance status.
	 *
	 * @return the user uuid of this application instance status
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this application instance status.
	 *
	 * @param userUuid the user uuid of this application instance status
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this application instance status.
	 *
	 * @return the user name of this application instance status
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this application instance status.
	 *
	 * @param userName the user name of this application instance status
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this application instance status.
	 *
	 * @return the create date of this application instance status
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this application instance status.
	 *
	 * @param createDate the create date of this application instance status
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application instance status.
	 *
	 * @return the modified date of this application instance status
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application instance status.
	 *
	 * @param modifiedDate the modified date of this application instance status
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the application instance ID of this application instance status.
	 *
	 * @return the application instance ID of this application instance status
	 */
	public long getApplicationInstanceId();

	/**
	 * Sets the application instance ID of this application instance status.
	 *
	 * @param applicationInstanceId the application instance ID of this application instance status
	 */
	public void setApplicationInstanceId(long applicationInstanceId);

	/**
	 * Returns the status of this application instance status.
	 *
	 * @return the status of this application instance status
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this application instance status.
	 *
	 * @param status the status of this application instance status
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus applicationInstanceStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}