/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApplicationStoreItem service. Represents a row in the &quot;bibboxdocker_ApplicationStoreItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationStoreItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationStoreItemImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see ApplicationStoreItem
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationStoreItemImpl
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationStoreItemModelImpl
 * @generated
 */
@ProviderType
public interface ApplicationStoreItemModel extends BaseModel<ApplicationStoreItem>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application store item model instance should use the {@link ApplicationStoreItem} interface instead.
	 */

	/**
	 * Returns the primary key of this application store item.
	 *
	 * @return the primary key of this application store item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application store item.
	 *
	 * @param primaryKey the primary key of this application store item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application store item ID of this application store item.
	 *
	 * @return the application store item ID of this application store item
	 */
	public long getApplicationStoreItemId();

	/**
	 * Sets the application store item ID of this application store item.
	 *
	 * @param applicationStoreItemId the application store item ID of this application store item
	 */
	public void setApplicationStoreItemId(long applicationStoreItemId);

	/**
	 * Returns the group ID of this application store item.
	 *
	 * @return the group ID of this application store item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this application store item.
	 *
	 * @param groupId the group ID of this application store item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this application store item.
	 *
	 * @return the company ID of this application store item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this application store item.
	 *
	 * @param companyId the company ID of this application store item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this application store item.
	 *
	 * @return the user ID of this application store item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this application store item.
	 *
	 * @param userId the user ID of this application store item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this application store item.
	 *
	 * @return the user uuid of this application store item
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this application store item.
	 *
	 * @param userUuid the user uuid of this application store item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this application store item.
	 *
	 * @return the user name of this application store item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this application store item.
	 *
	 * @param userName the user name of this application store item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this application store item.
	 *
	 * @return the create date of this application store item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this application store item.
	 *
	 * @param createDate the create date of this application store item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application store item.
	 *
	 * @return the modified date of this application store item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application store item.
	 *
	 * @param modifiedDate the modified date of this application store item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the githash of this application store item.
	 *
	 * @return the githash of this application store item
	 */
	@AutoEscape
	public String getGithash();

	/**
	 * Sets the githash of this application store item.
	 *
	 * @param githash the githash of this application store item
	 */
	public void setGithash(String githash);

	/**
	 * Returns the depreciated of this application store item.
	 *
	 * @return the depreciated of this application store item
	 */
	public Boolean getDepreciated();

	/**
	 * Sets the depreciated of this application store item.
	 *
	 * @param depreciated the depreciated of this application store item
	 */
	public void setDepreciated(Boolean depreciated);

	/**
	 * Returns the application folder name of this application store item.
	 *
	 * @return the application folder name of this application store item
	 */
	@AutoEscape
	public String getApplicationFolderName();

	/**
	 * Sets the application folder name of this application store item.
	 *
	 * @param applicationFolderName the application folder name of this application store item
	 */
	public void setApplicationFolderName(String applicationFolderName);

	/**
	 * Returns the application name of this application store item.
	 *
	 * @return the application name of this application store item
	 */
	@AutoEscape
	public String getApplicationName();

	/**
	 * Sets the application name of this application store item.
	 *
	 * @param applicationName the application name of this application store item
	 */
	public void setApplicationName(String applicationName);

	/**
	 * Returns the application short name of this application store item.
	 *
	 * @return the application short name of this application store item
	 */
	@AutoEscape
	public String getApplicationShortName();

	/**
	 * Sets the application short name of this application store item.
	 *
	 * @param applicationShortName the application short name of this application store item
	 */
	public void setApplicationShortName(String applicationShortName);

	/**
	 * Returns the application version of this application store item.
	 *
	 * @return the application version of this application store item
	 */
	@AutoEscape
	public String getApplicationVersion();

	/**
	 * Sets the application version of this application store item.
	 *
	 * @param applicationVersion the application version of this application store item
	 */
	public void setApplicationVersion(String applicationVersion);

	/**
	 * Returns the application release state of this application store item.
	 *
	 * @return the application release state of this application store item
	 */
	@AutoEscape
	public String getApplicationReleaseState();

	/**
	 * Sets the application release state of this application store item.
	 *
	 * @param applicationReleaseState the application release state of this application store item
	 */
	public void setApplicationReleaseState(String applicationReleaseState);

	/**
	 * Returns the application description of this application store item.
	 *
	 * @return the application description of this application store item
	 */
	@AutoEscape
	public String getApplicationDescription();

	/**
	 * Sets the application description of this application store item.
	 *
	 * @param applicationDescription the application description of this application store item
	 */
	public void setApplicationDescription(String applicationDescription);

	/**
	 * Returns the application catalogue url of this application store item.
	 *
	 * @return the application catalogue url of this application store item
	 */
	@AutoEscape
	public String getApplicationCatalogueUrl();

	/**
	 * Sets the application catalogue url of this application store item.
	 *
	 * @param applicationCatalogueUrl the application catalogue url of this application store item
	 */
	public void setApplicationCatalogueUrl(String applicationCatalogueUrl);

	/**
	 * Returns the application application url of this application store item.
	 *
	 * @return the application application url of this application store item
	 */
	@AutoEscape
	public String getApplicationApplicationUrl();

	/**
	 * Sets the application application url of this application store item.
	 *
	 * @param applicationApplicationUrl the application application url of this application store item
	 */
	public void setApplicationApplicationUrl(String applicationApplicationUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.liferay.portlet.model.ApplicationStoreItem applicationStoreItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.liferay.portlet.model.ApplicationStoreItem> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationStoreItem toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationStoreItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}