/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApplicationTag service. Represents a row in the &quot;bibboxdocker_ApplicationTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationTagModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationTagImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see ApplicationTag
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationTagImpl
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.ApplicationTagModelImpl
 * @generated
 */
@ProviderType
public interface ApplicationTagModel extends BaseModel<ApplicationTag>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application tag model instance should use the {@link ApplicationTag} interface instead.
	 */

	/**
	 * Returns the primary key of this application tag.
	 *
	 * @return the primary key of this application tag
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application tag.
	 *
	 * @param primaryKey the primary key of this application tag
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application tags ID of this application tag.
	 *
	 * @return the application tags ID of this application tag
	 */
	public long getApplicationTagsId();

	/**
	 * Sets the application tags ID of this application tag.
	 *
	 * @param applicationTagsId the application tags ID of this application tag
	 */
	public void setApplicationTagsId(long applicationTagsId);

	/**
	 * Returns the group ID of this application tag.
	 *
	 * @return the group ID of this application tag
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this application tag.
	 *
	 * @param groupId the group ID of this application tag
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this application tag.
	 *
	 * @return the company ID of this application tag
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this application tag.
	 *
	 * @param companyId the company ID of this application tag
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this application tag.
	 *
	 * @return the user ID of this application tag
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this application tag.
	 *
	 * @param userId the user ID of this application tag
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this application tag.
	 *
	 * @return the user uuid of this application tag
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this application tag.
	 *
	 * @param userUuid the user uuid of this application tag
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this application tag.
	 *
	 * @return the user name of this application tag
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this application tag.
	 *
	 * @param userName the user name of this application tag
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this application tag.
	 *
	 * @return the create date of this application tag
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this application tag.
	 *
	 * @param createDate the create date of this application tag
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application tag.
	 *
	 * @return the modified date of this application tag
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application tag.
	 *
	 * @param modifiedDate the modified date of this application tag
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tag of this application tag.
	 *
	 * @return the tag of this application tag
	 */
	@AutoEscape
	public String getTag();

	/**
	 * Sets the tag of this application tag.
	 *
	 * @param tag the tag of this application tag
	 */
	public void setTag(String tag);

	/**
	 * Returns the application store item ID of this application tag.
	 *
	 * @return the application store item ID of this application tag
	 */
	public long getApplicationStoreItemId();

	/**
	 * Sets the application store item ID of this application tag.
	 *
	 * @param applicationStoreItemId the application store item ID of this application tag
	 */
	public void setApplicationStoreItemId(long applicationStoreItemId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.liferay.portlet.model.ApplicationTag applicationTag);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.liferay.portlet.model.ApplicationTag> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationTag toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.ApplicationTag toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}