/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BibboxKit service. Represents a row in the &quot;bibboxdocker_BibboxKit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.BibboxKitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.liferay.portlet.model.impl.BibboxKitImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see BibboxKit
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.BibboxKitImpl
 * @see at.graz.meduni.bibbox.liferay.portlet.model.impl.BibboxKitModelImpl
 * @generated
 */
@ProviderType
public interface BibboxKitModel extends BaseModel<BibboxKit>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bibbox kit model instance should use the {@link BibboxKit} interface instead.
	 */

	/**
	 * Returns the primary key of this bibbox kit.
	 *
	 * @return the primary key of this bibbox kit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bibbox kit.
	 *
	 * @param primaryKey the primary key of this bibbox kit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bibbox kit ID of this bibbox kit.
	 *
	 * @return the bibbox kit ID of this bibbox kit
	 */
	public long getBibboxKitId();

	/**
	 * Sets the bibbox kit ID of this bibbox kit.
	 *
	 * @param bibboxKitId the bibbox kit ID of this bibbox kit
	 */
	public void setBibboxKitId(long bibboxKitId);

	/**
	 * Returns the group ID of this bibbox kit.
	 *
	 * @return the group ID of this bibbox kit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bibbox kit.
	 *
	 * @param groupId the group ID of this bibbox kit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bibbox kit.
	 *
	 * @return the company ID of this bibbox kit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bibbox kit.
	 *
	 * @param companyId the company ID of this bibbox kit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bibbox kit.
	 *
	 * @return the user ID of this bibbox kit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bibbox kit.
	 *
	 * @param userId the user ID of this bibbox kit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bibbox kit.
	 *
	 * @return the user uuid of this bibbox kit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bibbox kit.
	 *
	 * @param userUuid the user uuid of this bibbox kit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bibbox kit.
	 *
	 * @return the user name of this bibbox kit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bibbox kit.
	 *
	 * @param userName the user name of this bibbox kit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bibbox kit.
	 *
	 * @return the create date of this bibbox kit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bibbox kit.
	 *
	 * @param createDate the create date of this bibbox kit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bibbox kit.
	 *
	 * @return the modified date of this bibbox kit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bibbox kit.
	 *
	 * @param modifiedDate the modified date of this bibbox kit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the kit name of this bibbox kit.
	 *
	 * @return the kit name of this bibbox kit
	 */
	@AutoEscape
	public String getKitName();

	/**
	 * Sets the kit name of this bibbox kit.
	 *
	 * @param kitName the kit name of this bibbox kit
	 */
	public void setKitName(String kitName);

	/**
	 * Returns the application store item ID of this bibbox kit.
	 *
	 * @return the application store item ID of this bibbox kit
	 */
	public long getApplicationStoreItemId();

	/**
	 * Sets the application store item ID of this bibbox kit.
	 *
	 * @param applicationStoreItemId the application store item ID of this bibbox kit
	 */
	public void setApplicationStoreItemId(long applicationStoreItemId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.liferay.portlet.model.BibboxKit bibboxKit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.liferay.portlet.model.BibboxKit> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.BibboxKit toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.liferay.portlet.model.BibboxKit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}