/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.service.base;

import at.graz.meduni.bibbox.liferay.portlet.model.BibboxKit;
import at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitService;
import at.graz.meduni.bibbox.liferay.portlet.service.persistence.ApplicationStoreItemPersistence;
import at.graz.meduni.bibbox.liferay.portlet.service.persistence.ApplicationTagPersistence;
import at.graz.meduni.bibbox.liferay.portlet.service.persistence.BibboxKitPersistence;
import at.graz.meduni.bibbox.liferay.portlet.service.persistence.DockerContainerPersistence;
import at.graz.meduni.bibbox.liferay.portlet.service.persistence.KitGroupPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the bibbox kit remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link at.graz.meduni.bibbox.liferay.portlet.service.impl.BibboxKitServiceImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see at.graz.meduni.bibbox.liferay.portlet.service.impl.BibboxKitServiceImpl
 * @see at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitServiceUtil
 * @generated
 */
public abstract class BibboxKitServiceBaseImpl extends BaseServiceImpl
	implements BibboxKitService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitServiceUtil} to access the bibbox kit remote service.
	 */

	/**
	 * Returns the application store item local service.
	 *
	 * @return the application store item local service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemLocalService getApplicationStoreItemLocalService() {
		return applicationStoreItemLocalService;
	}

	/**
	 * Sets the application store item local service.
	 *
	 * @param applicationStoreItemLocalService the application store item local service
	 */
	public void setApplicationStoreItemLocalService(
		at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemLocalService applicationStoreItemLocalService) {
		this.applicationStoreItemLocalService = applicationStoreItemLocalService;
	}

	/**
	 * Returns the application store item remote service.
	 *
	 * @return the application store item remote service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemService getApplicationStoreItemService() {
		return applicationStoreItemService;
	}

	/**
	 * Sets the application store item remote service.
	 *
	 * @param applicationStoreItemService the application store item remote service
	 */
	public void setApplicationStoreItemService(
		at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemService applicationStoreItemService) {
		this.applicationStoreItemService = applicationStoreItemService;
	}

	/**
	 * Returns the application store item persistence.
	 *
	 * @return the application store item persistence
	 */
	public ApplicationStoreItemPersistence getApplicationStoreItemPersistence() {
		return applicationStoreItemPersistence;
	}

	/**
	 * Sets the application store item persistence.
	 *
	 * @param applicationStoreItemPersistence the application store item persistence
	 */
	public void setApplicationStoreItemPersistence(
		ApplicationStoreItemPersistence applicationStoreItemPersistence) {
		this.applicationStoreItemPersistence = applicationStoreItemPersistence;
	}

	/**
	 * Returns the application tag local service.
	 *
	 * @return the application tag local service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagLocalService getApplicationTagLocalService() {
		return applicationTagLocalService;
	}

	/**
	 * Sets the application tag local service.
	 *
	 * @param applicationTagLocalService the application tag local service
	 */
	public void setApplicationTagLocalService(
		at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagLocalService applicationTagLocalService) {
		this.applicationTagLocalService = applicationTagLocalService;
	}

	/**
	 * Returns the application tag remote service.
	 *
	 * @return the application tag remote service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagService getApplicationTagService() {
		return applicationTagService;
	}

	/**
	 * Sets the application tag remote service.
	 *
	 * @param applicationTagService the application tag remote service
	 */
	public void setApplicationTagService(
		at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagService applicationTagService) {
		this.applicationTagService = applicationTagService;
	}

	/**
	 * Returns the application tag persistence.
	 *
	 * @return the application tag persistence
	 */
	public ApplicationTagPersistence getApplicationTagPersistence() {
		return applicationTagPersistence;
	}

	/**
	 * Sets the application tag persistence.
	 *
	 * @param applicationTagPersistence the application tag persistence
	 */
	public void setApplicationTagPersistence(
		ApplicationTagPersistence applicationTagPersistence) {
		this.applicationTagPersistence = applicationTagPersistence;
	}

	/**
	 * Returns the bibbox kit local service.
	 *
	 * @return the bibbox kit local service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitLocalService getBibboxKitLocalService() {
		return bibboxKitLocalService;
	}

	/**
	 * Sets the bibbox kit local service.
	 *
	 * @param bibboxKitLocalService the bibbox kit local service
	 */
	public void setBibboxKitLocalService(
		at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitLocalService bibboxKitLocalService) {
		this.bibboxKitLocalService = bibboxKitLocalService;
	}

	/**
	 * Returns the bibbox kit remote service.
	 *
	 * @return the bibbox kit remote service
	 */
	public BibboxKitService getBibboxKitService() {
		return bibboxKitService;
	}

	/**
	 * Sets the bibbox kit remote service.
	 *
	 * @param bibboxKitService the bibbox kit remote service
	 */
	public void setBibboxKitService(BibboxKitService bibboxKitService) {
		this.bibboxKitService = bibboxKitService;
	}

	/**
	 * Returns the bibbox kit persistence.
	 *
	 * @return the bibbox kit persistence
	 */
	public BibboxKitPersistence getBibboxKitPersistence() {
		return bibboxKitPersistence;
	}

	/**
	 * Sets the bibbox kit persistence.
	 *
	 * @param bibboxKitPersistence the bibbox kit persistence
	 */
	public void setBibboxKitPersistence(
		BibboxKitPersistence bibboxKitPersistence) {
		this.bibboxKitPersistence = bibboxKitPersistence;
	}

	/**
	 * Returns the docker container local service.
	 *
	 * @return the docker container local service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerLocalService getDockerContainerLocalService() {
		return dockerContainerLocalService;
	}

	/**
	 * Sets the docker container local service.
	 *
	 * @param dockerContainerLocalService the docker container local service
	 */
	public void setDockerContainerLocalService(
		at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerLocalService dockerContainerLocalService) {
		this.dockerContainerLocalService = dockerContainerLocalService;
	}

	/**
	 * Returns the docker container remote service.
	 *
	 * @return the docker container remote service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerService getDockerContainerService() {
		return dockerContainerService;
	}

	/**
	 * Sets the docker container remote service.
	 *
	 * @param dockerContainerService the docker container remote service
	 */
	public void setDockerContainerService(
		at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerService dockerContainerService) {
		this.dockerContainerService = dockerContainerService;
	}

	/**
	 * Returns the docker container persistence.
	 *
	 * @return the docker container persistence
	 */
	public DockerContainerPersistence getDockerContainerPersistence() {
		return dockerContainerPersistence;
	}

	/**
	 * Sets the docker container persistence.
	 *
	 * @param dockerContainerPersistence the docker container persistence
	 */
	public void setDockerContainerPersistence(
		DockerContainerPersistence dockerContainerPersistence) {
		this.dockerContainerPersistence = dockerContainerPersistence;
	}

	/**
	 * Returns the kit group local service.
	 *
	 * @return the kit group local service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.KitGroupLocalService getKitGroupLocalService() {
		return kitGroupLocalService;
	}

	/**
	 * Sets the kit group local service.
	 *
	 * @param kitGroupLocalService the kit group local service
	 */
	public void setKitGroupLocalService(
		at.graz.meduni.bibbox.liferay.portlet.service.KitGroupLocalService kitGroupLocalService) {
		this.kitGroupLocalService = kitGroupLocalService;
	}

	/**
	 * Returns the kit group remote service.
	 *
	 * @return the kit group remote service
	 */
	public at.graz.meduni.bibbox.liferay.portlet.service.KitGroupService getKitGroupService() {
		return kitGroupService;
	}

	/**
	 * Sets the kit group remote service.
	 *
	 * @param kitGroupService the kit group remote service
	 */
	public void setKitGroupService(
		at.graz.meduni.bibbox.liferay.portlet.service.KitGroupService kitGroupService) {
		this.kitGroupService = kitGroupService;
	}

	/**
	 * Returns the kit group persistence.
	 *
	 * @return the kit group persistence
	 */
	public KitGroupPersistence getKitGroupPersistence() {
		return kitGroupPersistence;
	}

	/**
	 * Sets the kit group persistence.
	 *
	 * @param kitGroupPersistence the kit group persistence
	 */
	public void setKitGroupPersistence(KitGroupPersistence kitGroupPersistence) {
		this.kitGroupPersistence = kitGroupPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BibboxKitService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return BibboxKit.class;
	}

	protected String getModelClassName() {
		return BibboxKit.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = bibboxKitPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemLocalService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemLocalService applicationStoreItemLocalService;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.ApplicationStoreItemService applicationStoreItemService;
	@BeanReference(type = ApplicationStoreItemPersistence.class)
	protected ApplicationStoreItemPersistence applicationStoreItemPersistence;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagLocalService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagLocalService applicationTagLocalService;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.ApplicationTagService applicationTagService;
	@BeanReference(type = ApplicationTagPersistence.class)
	protected ApplicationTagPersistence applicationTagPersistence;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitLocalService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.BibboxKitLocalService bibboxKitLocalService;
	@BeanReference(type = BibboxKitService.class)
	protected BibboxKitService bibboxKitService;
	@BeanReference(type = BibboxKitPersistence.class)
	protected BibboxKitPersistence bibboxKitPersistence;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerLocalService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerLocalService dockerContainerLocalService;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.DockerContainerService dockerContainerService;
	@BeanReference(type = DockerContainerPersistence.class)
	protected DockerContainerPersistence dockerContainerPersistence;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.KitGroupLocalService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.KitGroupLocalService kitGroupLocalService;
	@BeanReference(type = at.graz.meduni.bibbox.liferay.portlet.service.KitGroupService.class)
	protected at.graz.meduni.bibbox.liferay.portlet.service.KitGroupService kitGroupService;
	@BeanReference(type = KitGroupPersistence.class)
	protected KitGroupPersistence kitGroupPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private BibboxKitServiceClpInvoker _clpInvoker = new BibboxKitServiceClpInvoker();
}