/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model.impl;

import aQute.bnd.annotation.ProviderType;

import at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus;
import at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatusModel;
import at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatusSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ApplicationInstanceStatus service. Represents a row in the &quot;bibboxdocker_ApplicationInstanceStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ApplicationInstanceStatusModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationInstanceStatusImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see ApplicationInstanceStatusImpl
 * @see ApplicationInstanceStatus
 * @see ApplicationInstanceStatusModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ApplicationInstanceStatusModelImpl extends BaseModelImpl<ApplicationInstanceStatus>
	implements ApplicationInstanceStatusModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application instance status model instance should use the {@link ApplicationInstanceStatus} interface instead.
	 */
	public static final String TABLE_NAME = "bibboxdocker_ApplicationInstanceStatus";
	public static final Object[][] TABLE_COLUMNS = {
			{ "applicationInstanceStatusId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "applicationInstanceId", Types.BIGINT },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("applicationInstanceStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("applicationInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table bibboxdocker_ApplicationInstanceStatus (applicationInstanceStatusId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,applicationInstanceId LONG,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table bibboxdocker_ApplicationInstanceStatus";
	public static final String ORDER_BY_JPQL = " ORDER BY applicationInstanceStatus.applicationInstanceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY bibboxdocker_ApplicationInstanceStatus.applicationInstanceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus"),
			true);
	public static final long APPLICATIONINSTANCEID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ApplicationInstanceStatus toModel(
		ApplicationInstanceStatusSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ApplicationInstanceStatus model = new ApplicationInstanceStatusImpl();

		model.setApplicationInstanceStatusId(soapModel.getApplicationInstanceStatusId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setApplicationInstanceId(soapModel.getApplicationInstanceId());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ApplicationInstanceStatus> toModels(
		ApplicationInstanceStatusSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ApplicationInstanceStatus> models = new ArrayList<ApplicationInstanceStatus>(soapModels.length);

		for (ApplicationInstanceStatusSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus"));

	public ApplicationInstanceStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _applicationInstanceStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setApplicationInstanceStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _applicationInstanceStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationInstanceStatus.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationInstanceStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("applicationInstanceStatusId",
			getApplicationInstanceStatusId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("applicationInstanceId", getApplicationInstanceId());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long applicationInstanceStatusId = (Long)attributes.get(
				"applicationInstanceStatusId");

		if (applicationInstanceStatusId != null) {
			setApplicationInstanceStatusId(applicationInstanceStatusId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long applicationInstanceId = (Long)attributes.get(
				"applicationInstanceId");

		if (applicationInstanceId != null) {
			setApplicationInstanceId(applicationInstanceId);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getApplicationInstanceStatusId() {
		return _applicationInstanceStatusId;
	}

	@Override
	public void setApplicationInstanceStatusId(long applicationInstanceStatusId) {
		_applicationInstanceStatusId = applicationInstanceStatusId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getApplicationInstanceId() {
		return _applicationInstanceId;
	}

	@Override
	public void setApplicationInstanceId(long applicationInstanceId) {
		_columnBitmask = -1L;

		if (!_setOriginalApplicationInstanceId) {
			_setOriginalApplicationInstanceId = true;

			_originalApplicationInstanceId = _applicationInstanceId;
		}

		_applicationInstanceId = applicationInstanceId;
	}

	public long getOriginalApplicationInstanceId() {
		return _originalApplicationInstanceId;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ApplicationInstanceStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ApplicationInstanceStatus toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ApplicationInstanceStatus)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationInstanceStatusImpl applicationInstanceStatusImpl = new ApplicationInstanceStatusImpl();

		applicationInstanceStatusImpl.setApplicationInstanceStatusId(getApplicationInstanceStatusId());
		applicationInstanceStatusImpl.setGroupId(getGroupId());
		applicationInstanceStatusImpl.setCompanyId(getCompanyId());
		applicationInstanceStatusImpl.setUserId(getUserId());
		applicationInstanceStatusImpl.setUserName(getUserName());
		applicationInstanceStatusImpl.setCreateDate(getCreateDate());
		applicationInstanceStatusImpl.setModifiedDate(getModifiedDate());
		applicationInstanceStatusImpl.setApplicationInstanceId(getApplicationInstanceId());
		applicationInstanceStatusImpl.setStatus(getStatus());

		applicationInstanceStatusImpl.resetOriginalValues();

		return applicationInstanceStatusImpl;
	}

	@Override
	public int compareTo(ApplicationInstanceStatus applicationInstanceStatus) {
		int value = 0;

		if (getApplicationInstanceId() < applicationInstanceStatus.getApplicationInstanceId()) {
			value = -1;
		}
		else if (getApplicationInstanceId() > applicationInstanceStatus.getApplicationInstanceId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ApplicationInstanceStatus)) {
			return false;
		}

		ApplicationInstanceStatus applicationInstanceStatus = (ApplicationInstanceStatus)obj;

		long primaryKey = applicationInstanceStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ApplicationInstanceStatusModelImpl applicationInstanceStatusModelImpl = this;

		applicationInstanceStatusModelImpl._setModifiedDate = false;

		applicationInstanceStatusModelImpl._originalApplicationInstanceId = applicationInstanceStatusModelImpl._applicationInstanceId;

		applicationInstanceStatusModelImpl._setOriginalApplicationInstanceId = false;

		applicationInstanceStatusModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationInstanceStatus> toCacheModel() {
		ApplicationInstanceStatusCacheModel applicationInstanceStatusCacheModel = new ApplicationInstanceStatusCacheModel();

		applicationInstanceStatusCacheModel.applicationInstanceStatusId = getApplicationInstanceStatusId();

		applicationInstanceStatusCacheModel.groupId = getGroupId();

		applicationInstanceStatusCacheModel.companyId = getCompanyId();

		applicationInstanceStatusCacheModel.userId = getUserId();

		applicationInstanceStatusCacheModel.userName = getUserName();

		String userName = applicationInstanceStatusCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			applicationInstanceStatusCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			applicationInstanceStatusCacheModel.createDate = createDate.getTime();
		}
		else {
			applicationInstanceStatusCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			applicationInstanceStatusCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			applicationInstanceStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		applicationInstanceStatusCacheModel.applicationInstanceId = getApplicationInstanceId();

		applicationInstanceStatusCacheModel.status = getStatus();

		String status = applicationInstanceStatusCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			applicationInstanceStatusCacheModel.status = null;
		}

		return applicationInstanceStatusCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{applicationInstanceStatusId=");
		sb.append(getApplicationInstanceStatusId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", applicationInstanceId=");
		sb.append(getApplicationInstanceId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append(
			"at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceStatus");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>applicationInstanceStatusId</column-name><column-value><![CDATA[");
		sb.append(getApplicationInstanceStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicationInstanceId</column-name><column-value><![CDATA[");
		sb.append(getApplicationInstanceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ApplicationInstanceStatus.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ApplicationInstanceStatus.class
		};
	private long _applicationInstanceStatusId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _applicationInstanceId;
	private long _originalApplicationInstanceId;
	private boolean _setOriginalApplicationInstanceId;
	private String _status;
	private long _columnBitmask;
	private ApplicationInstanceStatus _escapedModel;
}