/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.liferay.portlet.model.impl;

import aQute.bnd.annotation.ProviderType;

import at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainer;
import at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainerModel;
import at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainerSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ApplicationInstanceContainer service. Represents a row in the &quot;bibboxdocker_ApplicationInstanceContainer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ApplicationInstanceContainerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationInstanceContainerImpl}.
 * </p>
 *
 * @author Robert Reihs
 * @see ApplicationInstanceContainerImpl
 * @see ApplicationInstanceContainer
 * @see ApplicationInstanceContainerModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ApplicationInstanceContainerModelImpl extends BaseModelImpl<ApplicationInstanceContainer>
	implements ApplicationInstanceContainerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application instance container model instance should use the {@link ApplicationInstanceContainer} interface instead.
	 */
	public static final String TABLE_NAME = "bibboxdocker_ApplicationInstanceContainer";
	public static final Object[][] TABLE_COLUMNS = {
			{ "applicationInstanceContainerId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "containerName", Types.VARCHAR },
			{ "needrunning", Types.BOOLEAN },
			{ "applicationInstanceId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("applicationInstanceContainerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("containerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("needrunning", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("applicationInstanceId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table bibboxdocker_ApplicationInstanceContainer (applicationInstanceContainerId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,containerName VARCHAR(75) null,needrunning BOOLEAN,applicationInstanceId LONG)";
	public static final String TABLE_SQL_DROP = "drop table bibboxdocker_ApplicationInstanceContainer";
	public static final String ORDER_BY_JPQL = " ORDER BY applicationInstanceContainer.applicationInstanceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY bibboxdocker_ApplicationInstanceContainer.applicationInstanceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainer"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainer"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainer"),
			true);
	public static final long APPLICATIONINSTANCEID_COLUMN_BITMASK = 1L;
	public static final long NEEDRUNNING_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ApplicationInstanceContainer toModel(
		ApplicationInstanceContainerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ApplicationInstanceContainer model = new ApplicationInstanceContainerImpl();

		model.setApplicationInstanceContainerId(soapModel.getApplicationInstanceContainerId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setContainerName(soapModel.getContainerName());
		model.setNeedrunning(soapModel.getNeedrunning());
		model.setApplicationInstanceId(soapModel.getApplicationInstanceId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ApplicationInstanceContainer> toModels(
		ApplicationInstanceContainerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ApplicationInstanceContainer> models = new ArrayList<ApplicationInstanceContainer>(soapModels.length);

		for (ApplicationInstanceContainerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainer"));

	public ApplicationInstanceContainerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _applicationInstanceContainerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setApplicationInstanceContainerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _applicationInstanceContainerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationInstanceContainer.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationInstanceContainer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("applicationInstanceContainerId",
			getApplicationInstanceContainerId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("containerName", getContainerName());
		attributes.put("needrunning", getNeedrunning());
		attributes.put("applicationInstanceId", getApplicationInstanceId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long applicationInstanceContainerId = (Long)attributes.get(
				"applicationInstanceContainerId");

		if (applicationInstanceContainerId != null) {
			setApplicationInstanceContainerId(applicationInstanceContainerId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String containerName = (String)attributes.get("containerName");

		if (containerName != null) {
			setContainerName(containerName);
		}

		Boolean needrunning = (Boolean)attributes.get("needrunning");

		if (needrunning != null) {
			setNeedrunning(needrunning);
		}

		Long applicationInstanceId = (Long)attributes.get(
				"applicationInstanceId");

		if (applicationInstanceId != null) {
			setApplicationInstanceId(applicationInstanceId);
		}
	}

	@JSON
	@Override
	public long getApplicationInstanceContainerId() {
		return _applicationInstanceContainerId;
	}

	@Override
	public void setApplicationInstanceContainerId(
		long applicationInstanceContainerId) {
		_applicationInstanceContainerId = applicationInstanceContainerId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getContainerName() {
		if (_containerName == null) {
			return StringPool.BLANK;
		}
		else {
			return _containerName;
		}
	}

	@Override
	public void setContainerName(String containerName) {
		_containerName = containerName;
	}

	@JSON
	@Override
	public boolean getNeedrunning() {
		return _needrunning;
	}

	@Override
	public boolean isNeedrunning() {
		return _needrunning;
	}

	@Override
	public void setNeedrunning(boolean needrunning) {
		_columnBitmask |= NEEDRUNNING_COLUMN_BITMASK;

		if (!_setOriginalNeedrunning) {
			_setOriginalNeedrunning = true;

			_originalNeedrunning = _needrunning;
		}

		_needrunning = needrunning;
	}

	public boolean getOriginalNeedrunning() {
		return _originalNeedrunning;
	}

	@JSON
	@Override
	public long getApplicationInstanceId() {
		return _applicationInstanceId;
	}

	@Override
	public void setApplicationInstanceId(long applicationInstanceId) {
		_columnBitmask = -1L;

		if (!_setOriginalApplicationInstanceId) {
			_setOriginalApplicationInstanceId = true;

			_originalApplicationInstanceId = _applicationInstanceId;
		}

		_applicationInstanceId = applicationInstanceId;
	}

	public long getOriginalApplicationInstanceId() {
		return _originalApplicationInstanceId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ApplicationInstanceContainer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ApplicationInstanceContainer toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ApplicationInstanceContainer)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationInstanceContainerImpl applicationInstanceContainerImpl = new ApplicationInstanceContainerImpl();

		applicationInstanceContainerImpl.setApplicationInstanceContainerId(getApplicationInstanceContainerId());
		applicationInstanceContainerImpl.setGroupId(getGroupId());
		applicationInstanceContainerImpl.setCompanyId(getCompanyId());
		applicationInstanceContainerImpl.setUserId(getUserId());
		applicationInstanceContainerImpl.setUserName(getUserName());
		applicationInstanceContainerImpl.setCreateDate(getCreateDate());
		applicationInstanceContainerImpl.setModifiedDate(getModifiedDate());
		applicationInstanceContainerImpl.setContainerName(getContainerName());
		applicationInstanceContainerImpl.setNeedrunning(getNeedrunning());
		applicationInstanceContainerImpl.setApplicationInstanceId(getApplicationInstanceId());

		applicationInstanceContainerImpl.resetOriginalValues();

		return applicationInstanceContainerImpl;
	}

	@Override
	public int compareTo(
		ApplicationInstanceContainer applicationInstanceContainer) {
		int value = 0;

		if (getApplicationInstanceId() < applicationInstanceContainer.getApplicationInstanceId()) {
			value = -1;
		}
		else if (getApplicationInstanceId() > applicationInstanceContainer.getApplicationInstanceId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ApplicationInstanceContainer)) {
			return false;
		}

		ApplicationInstanceContainer applicationInstanceContainer = (ApplicationInstanceContainer)obj;

		long primaryKey = applicationInstanceContainer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ApplicationInstanceContainerModelImpl applicationInstanceContainerModelImpl =
			this;

		applicationInstanceContainerModelImpl._setModifiedDate = false;

		applicationInstanceContainerModelImpl._originalNeedrunning = applicationInstanceContainerModelImpl._needrunning;

		applicationInstanceContainerModelImpl._setOriginalNeedrunning = false;

		applicationInstanceContainerModelImpl._originalApplicationInstanceId = applicationInstanceContainerModelImpl._applicationInstanceId;

		applicationInstanceContainerModelImpl._setOriginalApplicationInstanceId = false;

		applicationInstanceContainerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationInstanceContainer> toCacheModel() {
		ApplicationInstanceContainerCacheModel applicationInstanceContainerCacheModel =
			new ApplicationInstanceContainerCacheModel();

		applicationInstanceContainerCacheModel.applicationInstanceContainerId = getApplicationInstanceContainerId();

		applicationInstanceContainerCacheModel.groupId = getGroupId();

		applicationInstanceContainerCacheModel.companyId = getCompanyId();

		applicationInstanceContainerCacheModel.userId = getUserId();

		applicationInstanceContainerCacheModel.userName = getUserName();

		String userName = applicationInstanceContainerCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			applicationInstanceContainerCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			applicationInstanceContainerCacheModel.createDate = createDate.getTime();
		}
		else {
			applicationInstanceContainerCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			applicationInstanceContainerCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			applicationInstanceContainerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		applicationInstanceContainerCacheModel.containerName = getContainerName();

		String containerName = applicationInstanceContainerCacheModel.containerName;

		if ((containerName != null) && (containerName.length() == 0)) {
			applicationInstanceContainerCacheModel.containerName = null;
		}

		applicationInstanceContainerCacheModel.needrunning = getNeedrunning();

		applicationInstanceContainerCacheModel.applicationInstanceId = getApplicationInstanceId();

		return applicationInstanceContainerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{applicationInstanceContainerId=");
		sb.append(getApplicationInstanceContainerId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", containerName=");
		sb.append(getContainerName());
		sb.append(", needrunning=");
		sb.append(getNeedrunning());
		sb.append(", applicationInstanceId=");
		sb.append(getApplicationInstanceId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append(
			"at.graz.meduni.bibbox.liferay.portlet.model.ApplicationInstanceContainer");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>applicationInstanceContainerId</column-name><column-value><![CDATA[");
		sb.append(getApplicationInstanceContainerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>containerName</column-name><column-value><![CDATA[");
		sb.append(getContainerName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>needrunning</column-name><column-value><![CDATA[");
		sb.append(getNeedrunning());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicationInstanceId</column-name><column-value><![CDATA[");
		sb.append(getApplicationInstanceId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ApplicationInstanceContainer.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ApplicationInstanceContainer.class
		};
	private long _applicationInstanceContainerId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _containerName;
	private boolean _needrunning;
	private boolean _originalNeedrunning;
	private boolean _setOriginalNeedrunning;
	private long _applicationInstanceId;
	private long _originalApplicationInstanceId;
	private boolean _setOriginalApplicationInstanceId;
	private long _columnBitmask;
	private ApplicationInstanceContainer _escapedModel;
}